- name: Arch Setup
  hosts: localhost
  become: yes
  vars:
    source_key: "./ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    ansible_user: root
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git_setup.yml
    - include_tasks: tasks/dev.yml
    - include_tasks: dotfiles.yml
    - include_tasks: tasks/zsh.yml
