- name: Setup Server Key
  hosts: localhost
  become: yes
  vars:
    source_key: "./ssh/server_key"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/server_key"
  tasks:
    - name: Ensure .ssh directory exists
      file:
        dest: "{{ dest_key | dirname }}"
        mode: "0700"
        state: directory

    - name: Copy private key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: "0600"

    - name: Copy public key
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: "0644"

    - name: Add key to ssh-agent
      shell: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/server_key
