- name: Test sudo privileged
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Check if system is Arch Linux
      ansible.builtin.command: cat /etc/os-release
      register: os_release
