- name: Install dev tools via Homebrew
  community.general.homebrew:
    name:
      - node
      - yarn
      - typescript
      - go
      - tldr
      - duf
      - navi
    state: present
  tags:
    - dev
    - install
    - node

- name: Install ts-node via npm (no Homebrew formula)
  community.general.npm:
    name: ts-node
    global: true
  tags:
    - dev
    - install
    - node
