- name: Install nvim dependency
  package:
    name:
      - nodejs
      - neovim
      - luarocks
      - ripgrep
      - lazygit
    state: present
  tags:
    - nvim
    - install
  ignore_errors: true
