- name: Ensure .ssh directory exists
  ansible.builtin.file:
    dest: "{{ dest_key | dirname }}"
    mode: "0700"
    state: directory
  tags:
    - ssh
    - install

- name: Install ssh key
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: "0600"
  tags:
    - ssh
    - install

- name: Install ssh key public
  ansible.builtin.copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: "0644"
  tags:
    - ssh
    - install

- name: Install OpenSSH tools (Linux)
  ansible.builtin.package:
    name: openssh
    state: present
  when: ansible_facts['os_family'] != "Darwin"
  tags:
    - ssh
    - install

- name: Add ssh key to macOS Keychain
  ansible.builtin.shell: ssh-add --apple-use-keychain "{{ dest_key }}"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - ssh
    - install

- name: Add ssh key to ssh-agent (Linux)
  ansible.builtin.shell: |
    eval "$(ssh-agent -s)"
    ssh-add "{{ dest_key }}"
  when: ansible_facts['os_family'] != "Darwin"
  tags:
    - ssh
    - install
