- name: Install OpenSSH tools
  package:
    name: openssh
    state: present

- name: Ensure .ssh directory exists
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - ssh
    - install

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - ssh
    - Install

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - ssh
    - install

- name: Add ssh key
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_rsa
