- name: Install shell utilities via Homebrew
  community.general.homebrew:
    name:
      - zsh
      - fzf
      - fd
      - eza
      - zoxide
      - bat
      - python
      - wget
      - just
      - shellcheck
      - shfmt
      - gitleaks
    state: present
  tags:
    - zsh
    - install
