- name: Install packages
  package:
    name:
      - zsh
      - tmux
      - fzf
      - zoxide
    state: present
  tags:
    - zsh
    - install

- name: Change default shell to Zsh
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

  tags:
    - zsh
